[workspace]
resolver = "2"
members = [
  "helib-src",
  "helib-sys",
  "helib-test",
  # "helib-tool",
  # "openfhe-src",
  # "openfhe-sys",
  # "openfhe-tool",
  # "seal-src",
  # "seal-sys",
  # "seal-tool",
]

[workspace.package]
version = "0.0.1"
authors = ["Mark Van de Vyver <mark@ckrd.io>"]

edition = "2021"
rust-version = "1.72.0"

description = "The package provides a FHE source of choice."
documentation = "https://docs.rs/ckrd-zink-fhe-src"
homepage = "https://github.com/ckrd-network/zink-fhe-src"
repository = "https://github.com/ckrd-network/zink-fhe-src"
license = "Apache-2.0/MIT"
license-file = "LICENSE"
readme = "README.md"
categories = ["cryptography"]
keywords = ["FHE", "BFV", "BGV", "zero-knowledge"]

[workspace.dependencies]
helib-src = { path = "helib-src" }
helib-test = { path = "helib-test" }
cc = "1.0.79"
dirs = "5.0.1"
regex = { version = "1.6.0", default-features = false, features = ["std"] }
libc = { version = "0.2"  }
flate2 = { version = "1.0" }
tar = { version = "0.4", default-features = false }

[package]
name = "zink-fhe-src"
version.workspace = true
authors.workspace = true

edition.workspace = true
rust-version.workspace = true

description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

# [features]
# helib = ["helib-sys"]
# openfhe = ["openfhe-sys"]
# seal = ["seal-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
